### ISSUE TITLE
Why separate package?

### ISSUE THREAD

**Issue by emitanaka** [DanyangDai/cranscurb_package#1]
Aren't we working from here? https://github.com/numbats/cranscrub

**Comment by DanyangDai** [comment]
That one is for the paper and this repo for package? Or we keep using [https://github.com/DanyangDai/paper-rpkg-downloads](https://github.com/DanyangDai/paper-rpkg-downloads) for the paper and use the numbats for package development?

**Comment by emitanaka** [comment]
Sorry, I might be getting mixed up. I thought https://github.com/DanyangDai/paper-rpkg-downloads is for the paper but notice that there is a paper directory in `numbats/cranscrub` too. 

Let's do it so that `numbats/cranscrub` is the package and `DanyangDai/paper-rpkg-downloads` is the paper?

**Comment by DanyangDai** [comment]
No problems!
